# Generated by Django 3.0.9 on 2020-08-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_delivering',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
