# Generated by Django 3.0.8 on 2020-08-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200811_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_digital', models.BooleanField(blank=True, default=False, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Store')),
            ],
        ),
    ]
